### ISSUE TITLE
Возможна проблема с функцией merge.

### ISSUE THREAD

**Issue by OXAYAZA** [s-rayleigh/iridium-framework#1]
На самом деле просто хотел выдернуть [отсюда](https://github.com/s-rayleigh/iridium-framework/blob/master/src/js/core.js#L214) merge.
В случае если значениями ключей выступают узлы то начинают сливаться значения узлов что приводит к ошибкам. [Пример и возможное исправление](https://codepen.io/OXAYAZA/pen/VdbxZM).

**Comment by s-rayleigh** [comment]
Пофиксил.
Коммит: 42d6ca542b651a10db086723f715c98432bbe51f
